version: "3.9"

services:
  client-monitor:
    container_name: client-monitor
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "2222:2222"
    image: client-monitor
    restart: unless-stopped
    volumes: 
      - "./client/config.json:/usr/src/mina-node-monitor/client/config.json"
    pid: host
    networks:
      - client-monitor

networks:
  client-monitor:
    name: client-monitor
    driver: bridge
